name: App Release
# on:
  # release:
  #   types: [published]
on: workflow_dispatch
  inputs: 
    buildName:
      description: 'Release version (eg, 2.1.5)'
      required: true
      type: text
    buildNumber:
      description: 'Release number (eg, 25)'
      required: true
      type: number

jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Homiletics.xcworkspace' }}
      XC_SCHEME: ${{ 'Homiletics' }}
      BUILD_NAME: ${{ buildName }}
      BUILD_NUMBER: ${{ buildNumber }}
    steps:
      - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"

      - uses: actions/checkout@v2

      - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
  

